version: "3"
volumes: 
  pgdata:
  gem_home:

services:
  postgres:
    image: postgres:10.7
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: pgpassword
  rails:
    build: .
    image: rails-pg
    ports: 
      - 33000:3000
    volumes:
      - .:/rails-pg
      - gem_home:/usr/local/bundle
      - /app/.git
    depends_on:
      - postgres
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
